We import the required libraries and load the dataset

In [1]:
import pandas as pd
import numpy as np
!pip install researchpy
import researchpy
pd.set_option("display.max_rows",None,"display.max_columns", None)
import warnings
warnings.filterwarnings('always')

Requirement already satisfied: researchpy in c:\users\study\onedrive\desktop\du\business_intelligence\labs\venv\lib\site-packages (0.3.2)
Requirement already satisfied: scipy in c:\users\study\onedrive\desktop\du\business_intelligence\labs\venv\lib\site-packages (from researchpy) (1.8.0)
Requirement already satisfied: pandas in c:\users\study\onedrive\desktop\du\business_intelligence\labs\venv\lib\site-packages (from researchpy) (1.4.2)
Requirement already satisfied: statsmodels in c:\users\study\onedrive\desktop\du\business_intelligence\labs\venv\lib\site-packages (from researchpy) (0.13.2)
Requirement already satisfied: numpy in c:\users\study\onedrive\desktop\du\business_intelligence\labs\venv\lib\site-packages (from researchpy) (1.22.3)
Requirement already satisfied: patsy in c:\users\study\onedrive\desktop\du\business_intelligence\labs\venv\lib\site-packages (from researchpy) (0.5.2)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\study\onedrive\desktop\du\business_intelligence\labs\venv\lib\site-packages (from pandas->researchpy) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\study\onedrive\desktop\du\business_intelligence\labs\venv\lib\site-packages (from pandas->researchpy) (2022.1)
Requirement already satisfied: six in c:\users\study\onedrive\desktop\du\business_intelligence\labs\venv\lib\site-packages (from patsy->researchpy) (1.16.0)
Requirement already satisfied: packaging>=21.3 in c:\users\study\onedrive\desktop\du\business_intelligence\labs\venv\lib\site-packages (from statsmodels->researchpy) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\study\onedrive\desktop\du\business_intelligence\labs\venv\lib\site-packages (from packaging>=21.3->statsmodels->researchpy) (3.0.7)

WARNING: You are using pip version 22.0.4; however, version 22.1 is available.
You should consider upgrading via the 'c:\users\study\onedrive\desktop\du\business_intelligence\labs\venv\scripts\python.exe -m pip install --upgrade pip' command.

Column graphical_appearance_name correspond to product_pattern and perceived_colour_value_name corresponds to product_color to make the interpretation easier for the reader.

In [2]:
hmdata = pd.read_csv('C:/Users/Study/OneDrive/Desktop/DU/Business_Intelligence/Home_assignment_BI/dataset_hm.csv')
hmdata = hmdata.sample(frac=0.2, random_state=100)
hmdata.describe(include=object)
hmdata.shape
hmdata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15971 entries, 65748 to 24132
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   t_date                       15971 non-null  object
 1   product_type_no              15971 non-null  int64
 2   product_type_name            15971 non-null  object
 3   product_group_no             15971 non-null  int64
 4   product_group_name           15971 non-null  object
 5   graphical_appearance_no      15971 non-null  int64
 6   graphical_appearance_name    15971 non-null  object
 7   colour_group_code            15971 non-null  int64
 8   colour_group_name            15971 non-null  object
 9   perceived_colour_value_id    15971 non-null  int64
 10  perceived_colour_value_name  15971 non-null  object
 11  index_group_no               15971 non-null  int64
 12  index_group_name             15971 non-null  object
 13  Price                        15971 non-null  float64
dtypes: float64(1), int64(6), object(7)
memory usage: 1.8+ MB

Results generated by chi-square are more reliable if values in the table are greater than 5. Based on the output of the first iteration we remove product_group_name, graphical_appearance_name and perceived_colour_value_name which donâ€™t satisfy this condition. We name is dataframe hmdata_chi. 
To avoid the repetition of results we exclude the first iteration of chi-square test from the notebook.

In [3]:
hmdata_chi = hmdata[ (hmdata["product_group_name"] != "Nightwear") & (hmdata["product_group_name"] != "Swimwear") & (hmdata["product_group_name"] != "Shoes")]  
hmdata_chi = hmdata_chi[(hmdata["graphical_appearance_name"] != "Argyle") & (hmdata["graphical_appearance_name"] != "Contrast") & (hmdata["graphical_appearance_name"] != "Mesh")& (hmdata["graphical_appearance_name"] != "Metallic") & (hmdata["graphical_appearance_name"] != "Neps") & (hmdata["graphical_appearance_name"] != "Other pattern") & (hmdata["graphical_appearance_name"] != "Contrast") & (hmdata["graphical_appearance_name"] != "Slub") & (hmdata["graphical_appearance_name"] != "Transparent") & (hmdata["graphical_appearance_name"] != "Unknown")]  
hmdata_chi = hmdata_chi[(hmdata["perceived_colour_value_name"] != "Undefined")]
hmdata_chi.shape
hmdata_product = hmdata_chi["product_group_name"] 
hmdata_pattern = hmdata_chi["graphical_appearance_name"]
hmdata_color = hmdata_chi["perceived_colour_value_name"]

C:\Users\Study\AppData\Local\Temp\ipykernel_83900\3675479863.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  hmdata_chi = hmdata_chi[(hmdata["graphical_appearance_name"] != "Argyle") & (hmdata["graphical_appearance_name"] != "Contrast") & (hmdata["graphical_appearance_name"] != "Mesh")& (hmdata["graphical_appearance_name"] != "Metallic") & (hmdata["graphical_appearance_name"] != "Neps") & (hmdata["graphical_appearance_name"] != "Other pattern") & (hmdata["graphical_appearance_name"] != "Contrast") & (hmdata["graphical_appearance_name"] != "Slub") & (hmdata["graphical_appearance_name"] != "Transparent") & (hmdata["graphical_appearance_name"] != "Unknown")]
C:\Users\Study\AppData\Local\Temp\ipykernel_83900\3675479863.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  hmdata_chi = hmdata_chi[(hmdata["perceived_colour_value_name"] != "Undefined")]

Now we run chi-square test

To check association between hmdata_product, hmdata_pattern

In [4]:
crosstab_pattern, res_pattern, exp_pattern = researchpy.crosstab(hmdata_product, hmdata_pattern, test='chi-square', expected_freqs=True)
# cross table contained observed values
crosstab_pattern

                          graphical_appearance_name                          \
graphical_appearance_name          All over pattern Application/3D Chambray
product_group_name
Garment Full body                               782             31       18
Garment Lower body                              528             16       18
Garment Upper body                             1043            135       29
All                                            2353            182       65

                                                                      \
graphical_appearance_name Check Colour blocking Denim Dot Embroidery
product_group_name
Garment Full body            50              17    81  36         41
Garment Lower body          119              76   782  12         22
Garment Upper body          221             205   108  37        130
All                         390             298   971  85        193

                                                                         \
graphical_appearance_name Front print Glittering/Metallic Jacquard Lace
product_group_name
Garment Full body                  25                  22       24   70
Garment Lower body                 11                  23       16    7
Garment Upper body                511                  47       80   74
All                               547                  92      120  151

                                                                       \
graphical_appearance_name Melange Mixed solid/pattern Other structure
product_group_name
Garment Full body              42                   9              23
Garment Lower body            151                  17              56
Garment Upper body            763                  62             123
All                           956                  88             202


graphical_appearance_name Placement print Sequin Solid Stripe Treatment    All
product_group_name
Garment Full body                      36     29   927    126         9   2398
Garment Lower body                     77     20  1734    119        46   3850
Garment Upper body                    364    108  3742    500        47   8329
All                                   477    157  6403    745       102  14577

In [5]:
#chi-square estimate and p-value
res_pattern

                 Chi-square test    results
0  Pearson Chi-square ( 38.0) =   2908.6832
1                     p-value =      0.0000
2                  Cramer's V =      0.3159

In [6]:
#expected values
exp_pattern

                          graphical_appearance_name                            \
graphical_appearance_name          All over pattern Application/3D   Chambray
product_group_name
Garment Full body                        387.081978      29.940043  10.692872
Garment Lower body                       621.461892      48.068876  17.167456
Garment Upper body                      1344.456130     103.991082  37.139672

                                                                              \
graphical_appearance_name       Check Colour blocking       Denim        Dot
product_group_name
Garment Full body           64.157234       49.022707  159.735062  13.982987
Garment Lower body         103.004733       78.706181  256.455375  22.449750
Garment Upper body         222.838033      170.271112  554.809563  48.567263

                                                                       \
graphical_appearance_name  Embroidery Front print Glittering/Metallic
product_group_name
Garment Full body           31.749606   89.984633           15.134527
Garment Lower body          50.974137  144.470742           24.298553
Garment Upper body         110.276257  312.544625           52.566920

                                                             \
graphical_appearance_name   Jacquard       Lace     Melange
product_group_name
Garment Full body          19.740687  24.840365  157.267476
Garment Lower body         31.693764  39.881320  252.493654
Garment Upper body         68.565548  86.278315  546.238869

                                                                               \
graphical_appearance_name Mixed solid/pattern Other structure Placement print
product_group_name
Garment Full body                   14.476504       33.230157       78.469232
Garment Lower body                  23.242094       53.351170      125.982712
Garment Upper body                  50.281402      115.418673      272.548055


graphical_appearance_name     Sequin        Solid      Stripe  Treatment
product_group_name
Garment Full body          25.827399  1053.330178  122.556768  16.779584
Garment Lower body         41.466008  1691.126432  196.765452  26.939700
Garment Upper body         89.706593  3658.543390  425.677780  58.280716

To check association between hmdata_product, hmdata_color

In [7]:
crosstab_color, res_color, exp_color = researchpy.crosstab(hmdata_product, hmdata_color, test='chi-square', expected_freqs=True)

# cross table contained observed values
crosstab_color

                            perceived_colour_value_name                    \
perceived_colour_value_name                      Bright  Dark Dusty Light
product_group_name
Garment Full body                                   126   989         570
Garment Lower body                                  100  1849         722
Garment Upper body                                  382  3223        1819
All                                                 608  6061        3111


perceived_colour_value_name Light Medium Medium Dusty    All
product_group_name
Garment Full body             291    164          258   2398
Garment Lower body            304    134          741   3850
Garment Upper body           1482    503          920   8329
All                          2077    801         1919  14577

In [8]:
#expected values
exp_color

                            perceived_colour_value_name               \
perceived_colour_value_name                      Bright         Dark
product_group_name
Garment Full body                            100.019483   997.069219
Garment Lower body                           160.581738  1600.799204
Garment Upper body                           347.398779  3463.131577


perceived_colour_value_name  Dusty Light        Light      Medium Medium Dusty
product_group_name
Garment Full body             511.777320   341.678397  131.769088   315.686492
Garment Lower body            821.660836   548.566234  211.555876   506.836112
Garment Upper body           1777.561844  1186.755368  457.675036  1096.477396

In [9]:
#chi-square estimate and p-value
res_color

                 Chi-square test   results
0  Pearson Chi-square ( 10.0) =   485.8657
1                     p-value =     0.0000
2                  Cramer's V =     0.1291

The result shows us that product pattern and product colour have a chi-square estimate of 2909.8 and 485.8 respectively which is much greater than their respective critical values. Hence, we conclude that there is definite association between dependent and independent variables. This perception is further strengthened by the significant p-values generated by the model.